---
apiVersion: v1
kind: Service
metadata:
  namespace: prow
  name: deck
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "backend-config-iap"}'
spec:
  selector:
    app: deck
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
