---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcs-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-west-1
    kind: SecretStore
  target:
    name: gcs-credentials
    creationPolicy: Owner
  data:
  - secretKey: "service-account.json"
    remoteRef:
      key: prow/gcs-credentials
