
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-us-west-1
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: aws-secrets-sa
