
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-sa
  annotations:
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/role-arn: arn:aws:iam::605126514283:role/prow-secrets-manager-role-tanzu-test-infra-service
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "86400"
