---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcs-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-east-1
    kind: SecretStore
  target:
    name: gcs-credentials
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: prow-service/gcs-credentials
      property: service-account.json
