---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cookie
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-east-1
    kind: SecretStore
  target:
    name: cookie
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: prow-service/cookie
      property: secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcs-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-east-1
    kind: SecretStore
  target:
    name: gcs-credentials
    creationPolicy: Owner
  data:
  - secretKey: "service-account.json"
    remoteRef:
      key: prow-service/gcs-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-east-1
    kind: SecretStore
  target:
    name: github-oauth-config
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: prow-service/github-oauth-config
      property: secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-east-1
    kind: SecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
  - secretKey: appid
    remoteRef:
      key: prow-service/github-appid
      property: appid
  - secretKey: cert
    remoteRef:
      key: prow-service/github-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hmac-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-us-east-1
    kind: SecretStore
  target:
    name: hmac-token
    creationPolicy: Owner
  data:
  - secretKey: hmac
    remoteRef:
      key: prow-service/hmac-token
      property: hmac
